package com.fanfan.robot.local.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.fanfan.robot.local.model.VoiceBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VOICE_BEAN".
*/
public class VoiceBeanDao extends AbstractDao<VoiceBean, Long> {

    public static final String TABLENAME = "VOICE_BEAN";

    /**
     * Properties of entity VoiceBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property SaveTime = new Property(1, long.class, "saveTime", false, "saveTime");
        public final static Property ShowTitle = new Property(2, String.class, "showTitle", false, "showTitle");
        public final static Property VoiceAnswer = new Property(3, String.class, "voiceAnswer", false, "voiceanswer");
        public final static Property Keyword = new Property(4, String.class, "keyword", false, "keyword");
        public final static Property Type = new Property(5, int.class, "type", false, "type");
        public final static Property Business = new Property(6, String.class, "business", false, "business");
        public final static Property Key1 = new Property(7, String.class, "key1", false, "key1");
        public final static Property Key2 = new Property(8, String.class, "key2", false, "key2");
        public final static Property Key3 = new Property(9, String.class, "key3", false, "key3");
        public final static Property Key4 = new Property(10, String.class, "key4", false, "key4");
    }


    public VoiceBeanDao(DaoConfig config) {
        super(config);
    }
    
    public VoiceBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VOICE_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"saveTime\" INTEGER NOT NULL ," + // 1: saveTime
                "\"showTitle\" TEXT," + // 2: showTitle
                "\"voiceanswer\" TEXT," + // 3: voiceAnswer
                "\"keyword\" TEXT," + // 4: keyword
                "\"type\" INTEGER NOT NULL ," + // 5: type
                "\"business\" TEXT," + // 6: business
                "\"key1\" TEXT," + // 7: key1
                "\"key2\" TEXT," + // 8: key2
                "\"key3\" TEXT," + // 9: key3
                "\"key4\" TEXT);"); // 10: key4
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VOICE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, VoiceBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getSaveTime());
 
        String showTitle = entity.getShowTitle();
        if (showTitle != null) {
            stmt.bindString(3, showTitle);
        }
 
        String voiceAnswer = entity.getVoiceAnswer();
        if (voiceAnswer != null) {
            stmt.bindString(4, voiceAnswer);
        }
 
        String keyword = entity.getKeyword();
        if (keyword != null) {
            stmt.bindString(5, keyword);
        }
        stmt.bindLong(6, entity.getType());
 
        String business = entity.getBusiness();
        if (business != null) {
            stmt.bindString(7, business);
        }
 
        String key1 = entity.getKey1();
        if (key1 != null) {
            stmt.bindString(8, key1);
        }
 
        String key2 = entity.getKey2();
        if (key2 != null) {
            stmt.bindString(9, key2);
        }
 
        String key3 = entity.getKey3();
        if (key3 != null) {
            stmt.bindString(10, key3);
        }
 
        String key4 = entity.getKey4();
        if (key4 != null) {
            stmt.bindString(11, key4);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, VoiceBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getSaveTime());
 
        String showTitle = entity.getShowTitle();
        if (showTitle != null) {
            stmt.bindString(3, showTitle);
        }
 
        String voiceAnswer = entity.getVoiceAnswer();
        if (voiceAnswer != null) {
            stmt.bindString(4, voiceAnswer);
        }
 
        String keyword = entity.getKeyword();
        if (keyword != null) {
            stmt.bindString(5, keyword);
        }
        stmt.bindLong(6, entity.getType());
 
        String business = entity.getBusiness();
        if (business != null) {
            stmt.bindString(7, business);
        }
 
        String key1 = entity.getKey1();
        if (key1 != null) {
            stmt.bindString(8, key1);
        }
 
        String key2 = entity.getKey2();
        if (key2 != null) {
            stmt.bindString(9, key2);
        }
 
        String key3 = entity.getKey3();
        if (key3 != null) {
            stmt.bindString(10, key3);
        }
 
        String key4 = entity.getKey4();
        if (key4 != null) {
            stmt.bindString(11, key4);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public VoiceBean readEntity(Cursor cursor, int offset) {
        VoiceBean entity = new VoiceBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // saveTime
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // showTitle
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // voiceAnswer
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // keyword
            cursor.getInt(offset + 5), // type
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // business
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // key1
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // key2
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // key3
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10) // key4
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, VoiceBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSaveTime(cursor.getLong(offset + 1));
        entity.setShowTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setVoiceAnswer(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setKeyword(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setType(cursor.getInt(offset + 5));
        entity.setBusiness(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setKey1(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setKey2(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setKey3(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setKey4(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(VoiceBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(VoiceBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(VoiceBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
